config/routes.rb
Rails.application.routes.draw do
  get 'herbs/tags', to: 'herbs#tags'
  resources :herbs
  root to: 'herbs#index'
  get 'tags/:tag', to: 'herbs#index', as: :tag
  get '/about', to: 'herbs#about'

  get '/ajirginthesky', to: 'herbs#new'
end

app/models/herb.rb
class Herb < ActiveRecord::Base
  acts_as_taggable
  validates_presence_of :name, :description



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  


end

app/controllers/herbs_controller.rb
class HerbsController < InheritedResources::Base
  actions :new, :edit, :show, :update


  def index
    if params[:tag]
      herb = Herb.find_by(:id)
      @herbs = Herb.tagged_with(params[:tag]).paginate(:per_page => 8, :page => params[:page])
      @title = ActsAsTaggableOn::Tag.find_by_name(params[:tag]).to_s.titleize
    else
      @herbs = Herb.order(:name).group(:name).paginate(:per_page => 8, :page => params[:page])
      @title = "Traditional Remedies"
    end
  end

  def create
    @herb = Herb.new(herb_params)
    if @herb.save
      flash[:notice] = "The herb was added"
      redirect_to ajirginthesky_path
    else
      flash[:error] = "Try again"
      render :new
    end
  end

  private
  def herb_params
    params.require(:herb).permit(:name, :latin_name, :description, :tag_list, :tag)
  end
end

app/views/herbs/_form.html.haml
%section
  .container
    .row
      .col-med-10-md-offset-1
        = bootstrap_form_for [@herb], html: {class: "form-horizontal"} do |f|
          %fieldset
            = f.text_field :name
            = f.text_field :latin_name
            = f.text_area :description
            = f.text_field :tag_list
          %fieldset.actions.form-group
            .col-sm-6.col-md-offset-3
              = f.submit(@herb.new_record? ? 'Add Herb' : 'Update Herb', class: 'btn btn-default')

app/views/herbs/about.html.haml
= render 'layouts/header', title: "About Traditional Remedy Resource"

%section.container
  .col-sm-8
    %p
      This site was made to compile traditional information about natural medicinal
      remedies from cultures the world over. The database is simple and easy to use. I intend
      to add a text-search feature in the future to make research even easier.

app/views/herbs/edit.html.haml
%header Edit Herb
%well
  = render 'form'

app/views/herbs/index.html.haml
= render 'layouts/header', title: @title
%container
  %article
    - @herbs.each do |herb|
      %well.col-md-8
        %br
        %span.h3= herb.name
        %br
        %br
        %span.h5= herb.latin_name
        %br
        %br
        %p= herb.description
        %br
        %p Associated Ailments: #{raw herb.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')}
  = will_paginate @herbs

app/views/herbs/new.html.haml
%header New Herb
%well
  = render 'form'

app/views/herbs/tags.html.haml
= render 'layouts/header', title: "Common Ailments"

%container
  #tag_cloud
    - tag_cloud Herb.tag_counts, %w[s m l] do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class

app/views/layouts/_header.html.haml
%p.lead
  %h2= title
%hr/  

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Traditional Remedy Resource
      .collapse.navbar-collapse.navbar-left#navbar-ex1-collapse
        %ul.nav.navbar-nav
          %li= link_to "Herbs", root_path
          %li= link_to "Ailments", herbs_tags_path
          %li= link_to "About", about_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title Traditional Remedy Resource
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %script{src: "//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"}
    %link{href: "stylesheets/elastislide.css", rel: "stylesheet", type: "text/css"}/
    %link{href: "stylesheets/custom.css", rel: "stylesheet", type: "text/css"}/
    %script{src: "javascripts/modernizr.custom.17475.js"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
    :css
      body {
          margin-top: 60px;
      }
  %body
    = render 'layouts/navigation'
    .container
      .row
        .col-lg-12
          = render 'layouts/messages'
          = yield
    %script{src: "javascripts/jquery-1.10.2.js"}
    %script{src: "javascripts/bootstrap.js"}